[package]
name = "three"
version = "0.2.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Three.js inspired 3D engine in Rust"
categories = ["graphics", "game-engines"]
keywords = ["gamedev", "graphics", "engine", "3D"]
homepage = "https://github.com/kvark/three-rs"
repository = "https://github.com/kvark/three-rs"
documentation = "https://docs.rs/three/"
exclude = ["doc", "bors.toml", ".travis.yml", "test_data"]

[lib]

[features]
default = ["opengl"]
"opengl" = ["gfx_device_gl", "gfx_window_glutin", "glutin"]

[dependencies]
bitflags = "0.9"
cgmath = { version = "0.15", features = ["mint"] }
froggy = "0.3"
genmesh = "0.5"
gfx = "0.16"
gltf = { path = "../gltf", version = "0.9" }
gltf-importer = { path = "../gltf/gltf-importer", version = "0.9" }
gltf-utils = { path = "../gltf/gltf-utils", version = "0.9" }
image = "0.13"
itertools = "0.6"
log = "0.3"
obj = { version = "0.6", features = ["genmesh"] }
mint = "0.4.2"
vec_map = "0.8"
winit = "0.7.5"
# OpenGL
gfx_device_gl = { version = "0.14", optional = true }
gfx_window_glutin = { version = "0.17", optional = true }
glutin = { version = "0.9", optional = true }

[dev-dependencies]
env_logger = "0.4"
rand = "0.3"

[[example]]
name = "lights"

[[example]]
name = "materials"

[[example]]
name = "obj"

[[example]]
name = "pbr"

[[example]]
name = "shapes"

[[example]]
name = "sprite"

[[example]]
name = "gltf"

[[example]]
name = "group"

[[example]]
name = "anim"

[[example]]
name = "aviator"
path = "examples/aviator/main.rs"
